/**
 * 常量
 */

let USER_SESSION_KEY = 'user'

let TYPE_ANDROID = 1
let TYPE_IOS = 2
let TYPE_OTHER = 0

let REGISTER_VERIFY_CODE_TYPE = 1
let LOGIN_VERIFY_CODE_TYPE = 2
let RESET_PASSWORD_VERIFY_CODE_TYPE = 3
let CHANGE_PASSWORD_VERIFY_CODE_TYPE = 4
let WITHDRAW_ORDER_ID = 14
let ADD_WITHDRAW_ADDRESS = 15

let SMS_SEND_TYPE = 1

let NOT_LOGIN_ERROR_CODE = 401000001

let COIN_RECHARGE_STATUS_PENDING = 10
let COIN_RECHARGE_STATUS_CONFIRMING = 15
let COIN_RECHARGE_STATUS_RECHARGED = 40
let COIN_RECHARGE_STATUS_OBSOLETED = 90
let COIN_RECHARGE_STATUS_PENDING_NAME = '待处理'
let COIN_RECHARGE_STATUS_CONFIRMING_NAME = '确认中'
let COIN_RECHARGE_STATUS_RECHARGED_NAME = '已充值'
let COIN_RECHARGE_STATUS_OBSOLETED_NAME = '已作废'
let COIN_RECHARGE_STATUS_UNDEFINED_NAME = '未定义'

let COIN_BORROW_STATUS_PAYING = 10
let COIN_BORROW_STATUS_PAY_SUCCESS = 20
let COIN_BORROW_STATUS_WARNING_LINE = 21
let COIN_BORROW_STATUS_MARGIN_CALL = 22
let COIN_BORROW_STATUS_FAILED = 25
let COIN_BORROW_STATUS_PREPAY = 26
let COIN_BORROW_STATUS_CLOSED_ACCOUNT = 30
let COIN_BORROW_STATUS_CLOSE_OUT = 40
let COIN_BORROW_STATUS_PAYING_NAME = '放款中'
let COIN_BORROW_STATUS_PAY_SUCCESS_NAME = '已放款'
let COIN_BORROW_STATUS_WARNING_LINE_NAME = '预警'
let COIN_BORROW_STATUS_MARGIN_CALL_NAME = '待补仓'
let COIN_BORROW_STATUS_FAILED_NAME = '放款失败'
let COIN_BORROW_STATUS_PREPAY_NAME = '提前还款中'
let COIN_BORROW_STATUS_CLOSED_ACCOUNT_NAME = '已结清'
let COIN_BORROW_STATUS_CLOSE_OUT_NAME = '已平仓'

let COIN_WITHDRAW_STATUS_PENDING = 10
let COIN_WITHDRAW_STATUS_HANDING = 15
let COIN_WITHDRAW_STATUS_WITHDRAW_SUCCESS = 20
let COIN_WITHDRAW_STATUS_WITHDRAW_FAILED = 30
let COIN_WITHDRAW_STATUS_OBSOLETED = 90
let COIN_WITHDRAW_STATUS_PENDING_NAME = '待处理'
let COIN_WITHDRAW_STATUS_HANDING_NAME = '提币中'
let COIN_WITHDRAW_STATUS_WITHDRAW_SUCCESS_NAME = '提币成功'
let COIN_WITHDRAW_STATUS_WITHDRAW_FAILED_NAME = '提币失败'
let COIN_WITHDRAW_STATUS_OBSOLETED_NAME = '已作废'

export {
  TYPE_ANDROID,
  TYPE_IOS,
  TYPE_OTHER,
  USER_SESSION_KEY,
  REGISTER_VERIFY_CODE_TYPE,
  LOGIN_VERIFY_CODE_TYPE,
  RESET_PASSWORD_VERIFY_CODE_TYPE,
  CHANGE_PASSWORD_VERIFY_CODE_TYPE,
  WITHDRAW_ORDER_ID,
  ADD_WITHDRAW_ADDRESS,
  SMS_SEND_TYPE,
  NOT_LOGIN_ERROR_CODE,
  COIN_RECHARGE_STATUS_PENDING,
  COIN_RECHARGE_STATUS_CONFIRMING,
  COIN_RECHARGE_STATUS_RECHARGED,
  COIN_RECHARGE_STATUS_OBSOLETED,
  COIN_RECHARGE_STATUS_PENDING_NAME,
  COIN_RECHARGE_STATUS_CONFIRMING_NAME,
  COIN_RECHARGE_STATUS_RECHARGED_NAME,
  COIN_RECHARGE_STATUS_OBSOLETED_NAME,
  COIN_RECHARGE_STATUS_UNDEFINED_NAME,
  COIN_BORROW_STATUS_PAYING,
  COIN_BORROW_STATUS_PAY_SUCCESS,
  COIN_BORROW_STATUS_WARNING_LINE,
  COIN_BORROW_STATUS_MARGIN_CALL,
  COIN_BORROW_STATUS_FAILED,
  COIN_BORROW_STATUS_PREPAY,
  COIN_BORROW_STATUS_CLOSED_ACCOUNT,
  COIN_BORROW_STATUS_CLOSE_OUT,
  COIN_BORROW_STATUS_PAYING_NAME,
  COIN_BORROW_STATUS_PAY_SUCCESS_NAME,
  COIN_BORROW_STATUS_WARNING_LINE_NAME,
  COIN_BORROW_STATUS_MARGIN_CALL_NAME,
  COIN_BORROW_STATUS_FAILED_NAME,
  COIN_BORROW_STATUS_PREPAY_NAME,
  COIN_BORROW_STATUS_CLOSED_ACCOUNT_NAME,
  COIN_BORROW_STATUS_CLOSE_OUT_NAME,
  COIN_WITHDRAW_STATUS_PENDING,
  COIN_WITHDRAW_STATUS_HANDING,
  COIN_WITHDRAW_STATUS_WITHDRAW_SUCCESS,
  COIN_WITHDRAW_STATUS_WITHDRAW_FAILED,
  COIN_WITHDRAW_STATUS_OBSOLETED,
  COIN_WITHDRAW_STATUS_PENDING_NAME,
  COIN_WITHDRAW_STATUS_HANDING_NAME,
  COIN_WITHDRAW_STATUS_WITHDRAW_SUCCESS_NAME,
  COIN_WITHDRAW_STATUS_WITHDRAW_FAILED_NAME,
  COIN_WITHDRAW_STATUS_OBSOLETED_NAME
}
